### ISSUE TITLE
Breaking pages on developer.mozilla.org (mdn docs)

### ISSUE THREAD

**Issue by grantwinney** [grantwinney/generate-links-for-headers-in-chrome#17]
The pages on developer.mozilla.org are not loading due to an exception being thrown.

```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at ki (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129796)
    at ki (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129869)
    at ki (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129869)
    at ki (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129901)
    at ki (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129869)
    at bi (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:129294)
    at Nu (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:142075)
    at t.unstable_runWithPriority (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:162894)
    at $a (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:85253)
    at Lu (https://developer.mozilla.org/static/js/4.b149388b.chunk.js:2:140236)
ii @ react-dom.production.min.js:216
```

The URL (if applicable) pertaining to my problem is:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by ehaughee** [comment]
This same thing happens on a number of my company's internal sites.  I've had to disable this add on for now.

**Comment by grantwinney** [comment]
I applied a fix for mdn. It's approved in the chrome store.. the version is 1.3.7. Hopefully it'll fix your other sites too.

**Comment by grantwinney** [comment]
I'm going to close this for now, but if you're still running into problems, just let me know.
